id: P000311
initial_creation_type: ocr
created_at: 12/03/2020
last_modified_at: 2021-12-16 15:33:23.158639
source_metadata:
  id: bdr:W28829
  title: དཔྱད་རྩོམ་ཚངས་པའི་ཐིག་རིས
  author: ''
  volumes:
    827c8b94aa4c4dbc8aa42da3462ab288:
      image_group_id: I5762
      title: ''
      volume_number: 1
      total_pages: 578
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
